### ISSUE TITLE
What are the Steps to connect Data Direct Cloud to Tableau?

### ISSUE THREAD

**Issue by natashasweety7** [tableau/tableau.github.io#5]
Hi,
We are planning to use Data Direct to connect our Rollbase data to Tableau. A data source has already been created to access the data from Rollbase. we have configured the General and OData settings so I can access it in [Tableau](https://mindmajix.com/tableau-training).
The data in Data Direct Cloud can't be accessed from Tableau, is there any solution?
Thanks In Advance
Saanvi S

**Comment by jdomingu** [comment]
Sorry to hear you're having trouble. Unfortunately, I don't have a good answer for you. I notice that you also posted to the community forums. That's typically the best place for questions like this.

If you don't hear back, you might want to look in the support portal and open a case:
<https://www.tableau.com/support>

Hope that works out!
